spring.datasource.url=jdbc:mysql://localhost:3306/agriconnect?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=6281654343
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=8081

app.jwtSecret=AgriConnectSecretKeyChangeMe1234567890ABCD
app.jwtExpirationMs=86400000
